// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {api} from '../models';

export function Cancel(arg1:string):Promise<void>;

export function Start(arg1:string):Promise<api.BootstrapView>;
