// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';
import {api} from '../models';

export function Snapshot(arg1:context.Context):Promise<api.HealthSnapshot>;
