// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {api} from '../models';

export function Resize(arg1:number,arg2:number):Promise<void>;

export function Send(arg1:string):Promise<void>;

export function Start():Promise<api.MasterStatusView>;

export function Status():Promise<api.MasterStatusView>;

export function Stop():Promise<void>;
