// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Resize(arg1, arg2) {
  return window['go']['api']['MasterAPI']['Resize'](arg1, arg2);
}

export function Send(arg1) {
  return window['go']['api']['MasterAPI']['Send'](arg1);
}

export function Start() {
  return window['go']['api']['MasterAPI']['Start']();
}

export function Status() {
  return window['go']['api']['MasterAPI']['Status']();
}

export function Stop() {
  return window['go']['api']['MasterAPI']['Stop']();
}
