// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {store} from '../models';

export function Create(arg1:store.CreateProjectInput):Promise<store.Project>;

export function Delete(arg1:string):Promise<void>;

export function List():Promise<Array<store.Project>>;
