// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Create(arg1) {
  return window['go']['api']['ProjectsAPI']['Create'](arg1);
}

export function Delete(arg1) {
  return window['go']['api']['ProjectsAPI']['Delete'](arg1);
}

export function List() {
  return window['go']['api']['ProjectsAPI']['List']();
}
