// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {api} from '../models';
import {http} from '../models';

export function Get(arg1:string):Promise<api.RunView>;

export function LocalHTTPBase():Promise<string>;

export function LogsHandler():Promise<http.Handler>;

export function Start(arg1:string):Promise<api.RunView>;

export function Stop(arg1:string):Promise<void>;
