// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Get(arg1) {
  return window['go']['api']['RunsAPI']['Get'](arg1);
}

export function LocalHTTPBase() {
  return window['go']['api']['RunsAPI']['LocalHTTPBase']();
}

export function LogsHandler() {
  return window['go']['api']['RunsAPI']['LogsHandler']();
}

export function Start(arg1) {
  return window['go']['api']['RunsAPI']['Start'](arg1);
}

export function Stop(arg1) {
  return window['go']['api']['RunsAPI']['Stop'](arg1);
}
