// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetTranscript(arg1) {
  return window['go']['api']['SessionsAPI']['GetTranscript'](arg1);
}

export function ListByTask(arg1) {
  return window['go']['api']['SessionsAPI']['ListByTask'](arg1);
}

export function Start(arg1) {
  return window['go']['api']['SessionsAPI']['Start'](arg1);
}

export function Stop(arg1) {
  return window['go']['api']['SessionsAPI']['Stop'](arg1);
}
