// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {sandbox} from '../models';
import {store} from '../models';

export function GetTranscript(arg1:string):Promise<Array<sandbox.TranscriptMessage>>;

export function ListByTask(arg1:string):Promise<Array<store.Session>>;

export function Start(arg1:string):Promise<store.Session>;

export function Stop(arg1:string):Promise<void>;
