// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {api} from '../models';
import {store} from '../models';

export function Create(arg1:api.CreateTaskInput):Promise<store.Task>;

export function Discard(arg1:string):Promise<void>;

export function Get(arg1:string):Promise<store.Task>;

export function List(arg1:Array<string>):Promise<Array<store.Task>>;

export function Patch(arg1:string,arg2:api.PatchTaskInput):Promise<store.Task>;
