// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Create(arg1) {
  return window['go']['api']['TasksAPI']['Create'](arg1);
}

export function Discard(arg1) {
  return window['go']['api']['TasksAPI']['Discard'](arg1);
}

export function Get(arg1) {
  return window['go']['api']['TasksAPI']['Get'](arg1);
}

export function List(arg1) {
  return window['go']['api']['TasksAPI']['List'](arg1);
}

export function Patch(arg1, arg2) {
  return window['go']['api']['TasksAPI']['Patch'](arg1, arg2);
}
