// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {api} from '../models';

export function Delete(arg1:string):Promise<void>;

export function ListByProject(arg1:string):Promise<Array<api.WorktreeRead>>;
